Use $HOME/bin rather than /usr/local/bin so everything is self contained in the user's home directory.

diff --git a/drunner-install b/drunner-install
--- a/drunner-install
+++ b/drunner-install
@@ -70,7 +70,8 @@ EOF
 # copydrfiles
 function copydrfiles {
    if [ -d "${ROOTPATH}/support" ]; then
-      rm -r "${ROOTPATH}/support"
+      chmod -R u+w "${ROOTPATH}/support"
+      rm -rf "${ROOTPATH}/support"
    fi
    mkdir -p "${ROOTPATH}/support"
    
@@ -82,15 +83,17 @@ function copydrfiles {
    if [ $? -ne 0 ]; then 
       echo "Failed to copy files.">&2 
       echo "You will need to reinstall dRunner.">&2
-      rm -r "${ROOTPATH}" "/etc/drunner"
+      rm -rf "${ROOTPATH}"
       exit 1
    fi  
    # set ownership and permissions.
    docker run --rm -v "${ROOTPATH}/support:/s" drunner/baseimage-alpine bash -c "chown -R $EUID:${GROUPS[0]} /s ; chmod -R 0500 /s ; chmod -R 0555 /s/run_on_service"
 
-   local E="/usr/local/bin"
+   local E="${HOME}/bin"
+   [ -d "$E" ] || { mkdir -p "$E" || die "Couldn't create $E" ; source ~/.profile ; }  
    local S="${ROOTPATH}/support"
-   docker run --rm -v "$E:$E" -v "$S:$S" drunner/baseimage-alpine bash -c "rm -f $E/drunner ; ln -s $S/drunner $E/drunner" || die "Couldn't create drunner symbolic link"
+   # docker run --rm -v "$E:$E" -v "$S:$S" drunner/baseimage-alpine bash -c "rm -f $E/drunner ; ln -s $S/drunner $E/drunner" || die "Couldn't create drunner symbolic link"
+   ln -s "$S/drunner" "$E/drunner"
 }
 
 #------------------------------------------------------------------------------------
