Minor tidying.

diff --git a/drunner-install b/drunner-install
--- a/drunner-install
+++ b/drunner-install
@@ -71,26 +71,26 @@ EOF
 
 # copydrfiles
 function copydrfiles {
-   if [ -d "${ROOTPATH}/support" ]; then
-      chmod -R u+w "${ROOTPATH}/support"
-      rm -rf "${ROOTPATH}/support"
-   fi
-   mkdir -p "${ROOTPATH}/support"
+   [ ! -d "${ROOTPATH}/support" ] || rm -rf "${ROOTPATH}/support"    || die "Couldn't remove old ${ROOTPATH}/support."
+   mkdir -p "${ROOTPATH}/support" || die "Couldn't create ${ROOTPATH}/support"
+   [ -d "${ROOTPATH}/services" ]  || mkdir -p "${ROOTPATH}/services" || die "Couldn't create ${ROOTPATH}/services"
+
+   # copy the support files from the install-support image onto the host.    
+   docker run --rm -it -v "${ROOTPATH}/support:/tempcopy" "${SUPPORTIMAGE}" \
+      /bin/bash -c "cp -r /support/* /tempcopy/"                             
    
-   if [ ! -d "${ROOTPATH}/services" ]; then
-      mkdir -p "${ROOTPATH}/services"
-   fi
-    
-   docker run --rm -it -v "${ROOTPATH}/support:/tempcopy" "${SUPPORTIMAGE}" /bin/bash -c "cp -r /support/* /tempcopy/"                             
    if [ $? -ne 0 ]; then 
       echo "Failed to copy files.">&2 
       echo "You will need to reinstall dRunner.">&2
       rm -rf "${ROOTPATH}"
       exit 1
    fi  
-   # set ownership and permissions.
-   docker run --rm -v "${ROOTPATH}/support:/s" drunner/baseimage-alpine bash -c "chown -R $EUID:${GROUPS[0]} /s ; chmod -R 0500 /s ; chmod -R 0555 /s/run_on_service"
+   
+   # set ownership and permissions for those support files (don't rely on what's in the container).
+   docker run --rm -v "${ROOTPATH}/support:/s" drunner/baseimage-alpine \
+      bash -c "chown -R $EUID:${GROUPS[0]} /s ; chmod -R 0500 /s ; chmod -R 0555 /s/run_on_service"
 
+   # set up the symbolic link so drunner is in the current users path.
    local E="${HOME}/bin"
    [ -d "$E" ] || { mkdir -p "$E" || die "Couldn't create $E" ; source ~/.profile ; }  
    local S="${ROOTPATH}/support"
